#!/bin/sh

#
# Start the fbcp service....
#

cd /home/pi/slp

case "$1" in
  start)
    printf "Starting fbcp: "
    ./fbcp & 
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping fbcp: "
    # TODO...
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
